config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :movies do
  	resources :reviews, only: [:create, :destroy]
  	get "search_imdb", on: :new
  	post "save_imdb/:imdb_id", on: :collection, action: "save_imdb", as: "save_from_imdb"
 
  end

  root 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	
	has_many :reviews
	has_attached_file :image,  :styles => { :standard => "400x600>", :medium => "325x500>", :thumb => "200x300>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


  def self.rating
  	%w(G PG PG-13 R NC-17)
  end

  def average_rating
    reviews.average(:rating) || 0.00
  end
  
  def rating_from_imdb
  	imdb_rating || 0.00
  end
  
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  
  def reviewed(movie)
  	reviews.map(&:movie_id).include?(movie.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :set_movie, except: [:index, :new, :create, :search_imdb, :save_imdb]
  rescue_from    ActiveRecord::RecordNotFound, with: :invalid_movie
  def index
  	@movies = Movie.all
  end

  def show
    response = HTTParty.get("http://trailersapi.com/trailers.json?movie="+ CGI.escape(@movie.title) + "&limit=1&width=570")
    @movie.trailer_url = response[0]["code"] unless response.empty?
  end

  def edit
  end

  def new
  	@movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
  	if @movie.save
  		redirect_to @movie, notice: "movie successfully created"
  	else
  		render 'new' , alert: "Something went wrong try again Plz"
  	end
  end

  def update
  	if @movie.update_attributes(movie_params)
  	  redirect_to @movie, notice: "movie successfully updated"
    else
      render 'edit' , alert: "Something went wrong try again Plz"
    end
  end

  def destroy
  	movie = @movie
  	@movie.destroy
  	redirect_to movies_path, notice: "the movie #{movie.name} was deleted"
  end

  #imdb method

  def search_imdb
    imdb = ImdbParty::Imdb.new(:anonymize => true)
    title = params[:imdb_search][:title]
    @imdb_movies = imdb.find_by_title(title)
    flash.now[:notice] = "The search returned #{@imdb_movies.size} movies"
    render 'imdb_create'
  end

  def save_imdb
    imdb_id = params[:imdb_id].remove('tt')
    film = Imdb::Movie.new(imdb_id)
    @movie = Movie.new
    @movie.title = film.title
    @movie.description = film.plot
    @movie.director = film.director.join(', ')
    @movie.duration = film.length
    @movie.release = film.release_date
    @movie.imdb_id = imdb_id
    @movie.imdb_rating = film.rating
    @movie.trailer_url = film.trailer_url
    @movie.image = URI.parse(film.poster)
    if @movie.save
      redirect_to @movie, notice: "movie successfully created"
    else
      render 'new' , alert: "Something went wrong try again Plz"
    end
  end

 	private

 	def set_movie
 		@movie = Movie.find(params[:id])
 	end

 	def movie_params
 		params[:movie].permit(:title, :description, :rating, :director, :duration, :release, :image)
    params[:search_imdb].permit(:title)
 	end

  def invalid_movie
    @movie = nil
    redirect_to root_path, alert: 'Sorry That movie doesn\'t exist in our database you may check later on or just look
    for another movie'
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :set_movie
	
	def create
		@review = @movie.reviews.build(review_params)
		@review.user = current_user
		@review.save
		redirect_to @movie,  notice: "Thank you for Reviewing"
	end

	def destroy
		@movie.reviews.find(params[:id]).destroy
		redirect_to @movie, notice: "Your review was deleted, Plz help us by reviewing movies whenever possible"
	end

	private

	def set_movie
		@movie = Movie.find(params[:movie_id])
	end

	def review_params
		params[:review].permit(:rating, :comment)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

	def imdb_lookup
			
	end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-#{name.eql?('notice') ? 'success' : 'danger' }") %>
<% end -%>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="<%= root_path %>">Moviews</a>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav menu-elements">
			<li class="active"><a href="<%= movies_path %>">Movies</a></li>
			<li><a href="#">About us</a></li>
		</ul>

	
		<% unless user_signed_in? %>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Log In", new_user_session_path %></li>
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
			</ul>
		<% else %>	
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><%= link_to "Edit Account", edit_user_registration_path %></li>
						<li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
					</ul>
				</li>
			</ul>

			<div class="navbar-right">
				<a href="<%= new_movie_path %>" class="navbar-btn btn btn-primary">New movie</a>
			</div>
		<% end -%>
		


		<form class="navbar-form navbar-right" role="search">
			<div class="form-group">
				<input type="text" class="form-control" placeholder="Search">
			</div>
			<button type="submit" class="btn btn-default">Submit</button>
		</form>
	</div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Quicksand:300,400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.css">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" language="javascript" src="//cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div class="container">
	<%= render 'layouts/flash' %>
	<%= yield %>
</div>




</body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for @movie do |f| %>
	<div class="form-inputs">
		<%= f.input :title %>
		<%= f.input :description, as: :summernote, input_html: {rows: 8} %>
		<%= f.input :director %>
		<%= f.input :release, label: 'Released Year' %>
		<%= f.input :duration, label: 'Length' %>
		<%= f.input :rating, as: :select, collection: Movie.rating %>
		<%= f.input :image, as: :file, label: 'Movie Poster' %>
	</div>
	<br>
	<div class="form-buttons">
		<%= f.button :submit, class: 'btn btn-primary' %>
		<%= link_to "Cancel", :back, class: 'btn btn-danger' %>
	</div>
<% end -%>
<br>

app/views/movies/edit.html.erb
<h1>You are editing <%= @movie.title %></h1>

<%= render 'form' %>

app/views/movies/imdb_create.html.erb
<%= link_to :back, class: "btn btn-default" do %>
	<i class="fa fa-arrow-left"> Back</i>
<% end -%>
<div class="imdb_movies_list">
	<h1 class="text-center">Choose your movie from the list</h1><br><br>
	<table class="table table-striped table-bordered table-responsive" id="movies_table">
		<thead>
			<tr>
				<th>Year</th>
				<th>Title</th>
				<th>IMDB ID</th>
				<th>Actions</th>
			</tr>
		</thead>

		<tfoot>
			<tr>
				<th>Year</th>
				<th>Title</th>
				<th>IMDB ID</th>
				<th>Actions</th>
			</tr>
		</tfoot>

		<tbody>
			<% @imdb_movies.each do  |movie| %>
				<tr>
					<td><%= movie[:year] %></td>
					<td><%= sanitize movie[:title] %></td>
					<td><%= movie[:imdb_id] %></td>
					<td><%= link_to "Save", save_from_imdb_movies_path(imdb_id: movie[:imdb_id]), method: :post,
					 class: "btn btn-info" %></td>
				</tr>
			<% end -%>
		</tbody>

	</table>

</div>
<br><br>


<script>
	$(document).ready(function(){
		$('#movies_table').DataTable({
			"order": []
		});
	});
</script>

app/views/movies/index.html.erb
<div class="home movies">	
	<% @movies.reverse.each_slice(4) do |movies| %>
		<div class="row center-block">	
			<% movies.each do |movie| %>
				<div class="col-md-3 ">
					<%= link_to movie_path(movie) do %>
						<%= image_tag movie.image(:thumb), class: 'img-responsive thumbnail img-rounded' do %>
									
						<% end -%>
					<% end -%>
				</div>
			<% end -%>
		</div>
	<% end -%>
</div>

app/views/movies/new.html.erb
<div class="col-md-8 center-block">
	<div class="row">
		<h1 class= "text-left use-imdb col-md-9">Create a Movie</h1>
		<div class="col-md-3 pull-right">
			<a href="#" class="btn btn-default" id="imdb_creator">Use IMDB</a>
		</div>
	</div>
	<%= render 'form' %>

	<div id="imdb_form">
		<%= simple_form_for :imdb_search, url: search_imdb_new_movie_path, method: :get do |f| -%>
		  <%= f.input :title %>
		  <%= f.button :submit, "Search IMDB" %>
		<% end %>
	</div>
</div>

app/views/movies/show.html.erb
<div class="row movie">
	<div class="col-md-4 thumbnail">
		<%= image_tag @movie.image(:medium), class: "img-responsive img-rounded" %>
	</div>
	<div class="col-md-8">
		<div class="row">
			<div class="col-md-9">
				<h1 class="title"><%= @movie.title %>  </h1><br>
			</div>
			<div class="col-md-3">
				<a class="btn btn-primary pull-right" data-toggle="modal" href='#trailer'> <i class="fa fa-play"></i> Watch trailer</a>
				<div class="modal fade" id="trailer">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
								<h4 class="modal-title">Trailer for : <%= @movie.title %></h4>
							</div>
							<div class="modal-body">
								<%= @movie.trailer_url.html_safe unless @movie.trailer_url.nil? %>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
							</div>
						</div>
					</div>
				</div>
			</div>	
		</div>
		<p id="description"><%= sanitize @movie.description %></p><br>
		<div class="panel panel-default">
			<!-- Default panel contents -->
			<div class="panel-heading">details of the movie " <%= @movie.title %> "</div>
				<table class="table">
					<tbody>
						<tr>
							<th>Director</th>
							<td><%= @movie.director %></td>
						</tr>
						<tr>
							<th>Rating</th>
							<td><%= @movie.rating %></td>
						</tr>
						<tr>
							<th>Length</th>
							<td><%= @movie.duration + "#{@movie.duration.eql?('NA') ? '' : ' mins'}" %> </td>
						</tr>
						<tr>
							<th>Released Date</th>
							<td><%= @movie.release %></td>
						</tr>
					</tbody>
				</table>
		</div>

		<table class="table table-bordered">
			<tr>
				<th>Average review  (<%= @movie.average_rating * 2 || 0.00 %>/10.0)</th>
				<th>IMDB review (<%= @movie.imdb_rating || 0.00 %>/10.0)</th>
			</tr>
			<tr>
				<td class='star-rating' data-score="<%= @movie.average_rating %>"></td>
				<td class='star-rating' data-score="<%= @movie.rating_from_imdb / 2 %>"></td>
			</tr>
		</table>
	</div>
	

	<div id="reviews" class="clearfix col-md-12">
		<hr>
		<h3><%= pluralize @movie.reviews.count , 'Review' %></h3>
		<hr>
		<%= render @movie.reviews.reverse %>
		<% if user_signed_in? %>
			<% if current_user.reviewed(@movie) %>
				<div class="text-center">
					<br>
					<h4>You have already reviewed this movie we are grateful for your contribution</h4>
					<i class="fa fa-smile-o fa-2x">Thank You</i>
				</div>
			<% else %>
				<br>
				<h3>New review</h3>
				<hr>
				<%= render 'reviews/form' %>
			<% end -%>
		<% else %>
			<div class="text-center">
				<h4>you need to log in before you can review</h4>
				<%= link_to "Log in", new_user_session_path, class:"btn btn-info" %>
			</div>
		<% end -%>
	</div>
</div>
<br><br>

<script>
	$(".star-rating").raty({
		readOnly: true,
		halfShow: true,
		path: '/assets/',
		score: function(){
			return $(this).attr('data-score');
		}
	});
</script>

app/views/reviews/_form.html.erb
<%= simple_form_for [@movie, @movie.reviews.build] do |f| %>
	<div class="form-inputs">
		<label for="rating">Rating</label>
		<div class="rating"></div><br>
		<%= f.input :comment, as: :text %>
	</div>
	<div class="form-buttons">
		<%= f.button :submit %>
	</div>
<% end -%>

<script>
	$(".rating").raty({
		scoreName: 'review[rating]',
		half: true,
		path: '/assets/'
	});
</script>

app/views/reviews/_review.html.erb
posted by <%= review.user.username %> | <%= time_ago_in_words(review.created_at)  %> ago
<div class="review well well-sm">
	<div class="star-rating" data-score="<%= review.rating %>"></div>
	<p><%= review.comment %></p>
</div>

<script>
	$(".star-rating").raty({
		readOnly: true,
		path: '/assets/',
		score: function(){
			return $(this).attr('data-score');
		}
	})
</script>